// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "928bcae6-ae65-4189-b18e-500d02efc4b0";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onPressureValChange();
void onAStatusChange();
void onBStatusChange();
void onGStatusChange();
void onRStatusChange();

int pressure_val;
bool a_status;
bool b_status;
bool g_status;
bool r_status;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(pressure_val, READWRITE, ON_CHANGE, onPressureValChange);
  ArduinoCloud.addProperty(a_status, READWRITE, ON_CHANGE, onAStatusChange);
  ArduinoCloud.addProperty(b_status, READWRITE, ON_CHANGE, onBStatusChange);
  ArduinoCloud.addProperty(g_status, READWRITE, ON_CHANGE, onGStatusChange);
  ArduinoCloud.addProperty(r_status, READWRITE, ON_CHANGE, onRStatusChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
